SET NOCOUNT ON
GO

IF EXISTS (SELECT * FROM sys.sysdatabases WHERE name='GXEvents') 
	DROP DATABASE GXEvents
GO

CREATE DATABASE GXEvents
GO

SET QUOTED_IDENTIFIER ON
GO

SET DATEFORMAT MDY
GO

USE GXEvents
GO

DROP TABLE IF EXISTS  dbo.Account
DROP TABLE IF EXISTS  dbo.GXEvent
GO

CREATE TABLE Account (
	AID			INT IDENTITY(1, 1)	NOT NULL PRIMARY KEY CLUSTERED,
	Gmail		NVARCHAR(100)		NOT NULL,
	LastSync	DATETIMEOFFSET		NOT NULL,
	Finished	INT							NOT NULL DEFAULT 0 CHECK (Finished >= 0),
	Missed		INT							NOT NULL DEFAULT 0 CHECK (Missed >= 0)
)
GO

CREATE INDEX Gmail ON dbo.Account(Gmail)
GO

CREATE TABLE GXEvent (
	EID					INT IDENTITY(1, 1)	NOT NULL PRIMARY KEY CLUSTERED,
	AID					INT							NOT NULL FOREIGN KEY REFERENCES dbo.Account(AID),
	GID					VARCHAR(300)	,
	Location			NVARCHAR(100),
	Summary			NVARCHAR(100)		NOT NULL,
	Description		NVARCHAR(300),
	StartDate			DATE						NOT NULL,
	StartDateTime	DATETIMEOFFSET	,
	EndDate			DATE						NOT NULL,
	EndDateTime	DATETIMEOFFSET	,
	ColorId				TINYINT					NOT NULL CHECK (ColorId > 0), CHECK (ColorId < 12)
)
GO

CREATE INDEX GID ON dbo.GXEvent(GID)
GO